Introduction to Pandas

What is Pandas ?

- A powerful library for data manipulation and analysis in python built on top of Numpy. Provides data structure like series and DataFrame

Why Use Pandas?

- Easy data Cleaning and Transformation.
- Efficient handling of large datasets.
- integration with other Python libraries like matplotlib and seaborn for visualization

In [48]:
print("Introduction To Pandas")

Introduction To Pandas

In [49]:
!pip install pandas

Requirement already satisfied: pandas in ./.venv/lib/python3.14/site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in ./.venv/lib/python3.14/site-packages (from pandas) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [50]:
!pip install --upgrade pip

Requirement already satisfied: pip in ./.venv/lib/python3.14/site-packages (26.1.2)

Key Data structures in pandas
- series
- DataFrame (2 dimensional)

In [51]:
import pandas as pd

In [52]:
s = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])

In [53]:
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

A Series is a labelled array and on the other hand list is not a labelled array

In [54]:
df = pd.DataFrame({"name" : ["Harry","rohan","heera"], "marks":[100,20,90]})

In [55]:
df

    name  marks
0  Harry    100
1  rohan     20
2  heera     90

In [56]:
df = pd.read_csv("Iris.csv")

In [57]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [58]:
df.head() # gives first 5 rows

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [59]:
df.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [60]:
df.describe() # describes this dataset , gives you count, mean, std, min, count ,25%,50%, 75%, max these are just summaries of what 25% of it contains in each row means just avg of it

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [61]:
df.info()
'''gives <class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    str
dtypes: float64(4), int64(1), str(1)
memory usage: 7.2 KB '''

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    str
dtypes: float64(4), int64(1), str(1)
memory usage: 7.2 KB

"gives <class 'pandas.DataFrame'>\nRangeIndex: 150 entries, 0 to 149\nData columns (total 6 columns):\n #   Column         Non-Null Count  Dtype\n---  ------         --------------  -----\n 0   Id             150 non-null    int64\n 1   SepalLengthCm  150 non-null    float64\n 2   SepalWidthCm   150 non-null    float64\n 3   PetalLengthCm  150 non-null    float64\n 4   PetalWidthCm   150 non-null    float64\n 5   Species        150 non-null    str\ndtypes: float64(4), int64(1), str(1)\nmemory usage: 7.2 KB "

Data Selection

In [62]:
df["Id"]

0        1
1        2
2        3
3        4
4        5
      ...
145    146
146    147
147    148
148    149
149    150
Name: Id, Length: 150, dtype: int64

In [63]:
type(df['Id']) # it is pandas series

pandas.Series

In [64]:
df[["Id","SepalLengthCm"]]

      Id  SepalLengthCm
0      1            5.1
1      2            4.9
2      3            4.7
3      4            4.6
4      5            5.0
..   ...            ...
145  146            6.7
146  147            6.3
147  148            6.5
148  149            6.2
149  150            5.9

[150 rows x 2 columns]

In [65]:
df.iloc[0] # gives the first row details

Id                         1
SepalLengthCm            5.1
SepalWidthCm             3.5
PetalLengthCm            1.4
PetalWidthCm             0.2
Species          Iris-setosa
Name: 0, dtype: object

In [66]:
type(df.iloc[0]) # as it is 1 dimensional we will be returned it's type as pandas series

pandas.Series

In [67]:
df2 = pd.read_csv("data.csv")

In [68]:
df2.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2          NaN
1   2            4.9           3.0            1.4           0.2          NaN
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [69]:
df2.dropna()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
7,8,5.0,3.4,1.5,0.2,Iris-setosa
8,9,4.4,2.9,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [70]:
df2.fillna(0)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,0
1,2,4.9,3.0,1.4,0.2,0
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [71]:
df2

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,NaN
1,2,4.9,3.0,1.4,0.2,NaN
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [72]:
df.rename(columns={'SepalLengthCm': "SL "}) # it creates a new dataFrame when we run this , basically doesn't takes place in original df

      Id  SL   SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0      1  5.1           3.5            1.4           0.2     Iris-setosa
1      2  4.9           3.0            1.4           0.2     Iris-setosa
2      3  4.7           3.2            1.3           0.2     Iris-setosa
3      4  4.6           3.1            1.5           0.2     Iris-setosa
4      5  5.0           3.6            1.4           0.2     Iris-setosa
..   ...  ...           ...            ...           ...             ...
145  146  6.7           3.0            5.2           2.3  Iris-virginica
146  147  6.3           2.5            5.0           1.9  Iris-virginica
147  148  6.5           3.0            5.2           2.0  Iris-virginica
148  149  6.2           3.4            5.4           2.3  Iris-virginica
149  150  5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 6 columns]

In [73]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [74]:
df.rename(columns={'SepalLengthCm': "SL"}, inplace=True) # this will makes changes in place

In [75]:
df

      Id   SL  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0      1  5.1           3.5            1.4           0.2     Iris-setosa
1      2  4.9           3.0            1.4           0.2     Iris-setosa
2      3  4.7           3.2            1.3           0.2     Iris-setosa
3      4  4.6           3.1            1.5           0.2     Iris-setosa
4      5  5.0           3.6            1.4           0.2     Iris-setosa
..   ...  ...           ...            ...           ...             ...
145  146  6.7           3.0            5.2           2.3  Iris-virginica
146  147  6.3           2.5            5.0           1.9  Iris-virginica
147  148  6.5           3.0            5.2           2.0  Iris-virginica
148  149  6.2           3.4            5.4           2.3  Iris-virginica
149  150  5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 6 columns]

In [76]:
df.describe()

               Id          SL  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000  150.000000    150.000000     150.000000    150.000000
mean    75.500000    5.843333      3.054000       3.758667      1.198667
std     43.445368    0.828066      0.433594       1.764420      0.763161
min      1.000000    4.300000      2.000000       1.000000      0.100000
25%     38.250000    5.100000      2.800000       1.600000      0.300000
50%     75.500000    5.800000      3.000000       4.350000      1.300000
75%    112.750000    6.400000      3.300000       5.100000      1.800000
max    150.000000    7.900000      4.400000       6.900000      2.500000

In [77]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SL             150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    str
dtypes: float64(4), int64(1), str(1)
memory usage: 7.2 KB

In [78]:

df['SL'] = df['SL'].astype(int)

In [79]:
df.info() # changes float to int

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SL             150 non-null    int64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    str
dtypes: float64(3), int64(2), str(1)
memory usage: 7.2 KB

In [80]:
df['SL'] = df['SL'].astype(str)

In [81]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SL             150 non-null    str
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    str
dtypes: float64(3), int64(1), str(2)
memory usage: 7.2 KB

In [82]:
# now that column 'SL' is str
df['SL'][0]

'5'

In [83]:
len(df)

150

In [84]:
df["zeros"] = [0 for i in range(len(df))]

In [85]:
df

      Id SL  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species  zeros
0      1  5           3.5            1.4           0.2     Iris-setosa      0
1      2  4           3.0            1.4           0.2     Iris-setosa      0
2      3  4           3.2            1.3           0.2     Iris-setosa      0
3      4  4           3.1            1.5           0.2     Iris-setosa      0
4      5  5           3.6            1.4           0.2     Iris-setosa      0
..   ... ..           ...            ...           ...             ...    ...
145  146  6           3.0            5.2           2.3  Iris-virginica      0
146  147  6           2.5            5.0           1.9  Iris-virginica      0
147  148  6           3.0            5.2           2.0  Iris-virginica      0
148  149  6           3.4            5.4           2.3  Iris-virginica      0
149  150  5           3.0            5.1           1.8  Iris-virginica      0

[150 rows x 7 columns]

In [86]:
def fx(a):
    return a *a

In [87]:
df['zeros'] = df["PetalLengthCm"].apply(fx)

In [88]:
df

      Id SL  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species  zeros
0      1  5           3.5            1.4           0.2     Iris-setosa   1.96
1      2  4           3.0            1.4           0.2     Iris-setosa   1.96
2      3  4           3.2            1.3           0.2     Iris-setosa   1.69
3      4  4           3.1            1.5           0.2     Iris-setosa   2.25
4      5  5           3.6            1.4           0.2     Iris-setosa   1.96
..   ... ..           ...            ...           ...             ...    ...
145  146  6           3.0            5.2           2.3  Iris-virginica  27.04
146  147  6           2.5            5.0           1.9  Iris-virginica  25.00
147  148  6           3.0            5.2           2.0  Iris-virginica  27.04
148  149  6           3.4            5.4           2.3  Iris-virginica  29.16
149  150  5           3.0            5.1           1.8  Iris-virginica  26.01

[150 rows x 7 columns]

In [ ]:
%%sql

In [89]:
df.to_csv("export.csv", index=False) # this way you can save your file in the folder, index = false removes all of its index at the starting which is unnecessary

hellow

In [91]:
df1 = pd.DataFrame({
    "name": ["Harry","rohan","heera"],
    "marks": [100,20,90]
})

In [92]:
df1

    name  marks
0  Harry    100
1  rohan     20
2  heera     90

In [93]:
df3 = pd.DataFrame({
    'name' : ["abc", "def",'ghi'],
    'marks':[100,20,90]
})

In [94]:
df3

  name  marks
0  abc    100
1  def     20
2  ghi     90

In [96]:
pd.concat([df1,df3]) # This is how you merge the two dataframes

    name  marks
0  Harry    100
1  rohan     20
2  heera     90
0    abc    100
1    def     20
2    ghi     90

In [103]:
df1 = pd.DataFrame({
    'name' : ['aryan', 'chris','tony'],
    'marks':[100,20,90]
})

In [98]:
df1

    name  marks
0  Harry    100
1  rohan     20
2  heera     90

In [104]:
df2 = pd.DataFrame({
    'name': ['aryan', 'chris','tony'],
    'roll' :[1001,12189,12178]
})

In [105]:
pd.merge(df1,df2, on='name') # The pandas will ignore the stuff that is not there in anyone of the df1, df2 it will only consider the stuff which is there in both of the dataframes.

    name  marks   roll
0  aryan    100   1001
1  chris     20  12189
2   tony     90  12178